onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/clk
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/inverse
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/reset_n
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/sink_eop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/sink_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/sink_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/sink_ready
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/sink_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/sink_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/sink_valid
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/source_eop
add wave -noupdate -expand /fft_ofdm_tb/fft_ofdm_inst/source_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/source_exp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/source_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/source_ready
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/source_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/source_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/source_valid
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_clk_bfm_clk_clk
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_rst_bfm_reset_reset
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_rst_bfm_reset_reset_ports_inv
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_bfm_conduit_inverse
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_bfm_conduit_sink_eop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_bfm_conduit_sink_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_bfm_conduit_sink_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_bfm_conduit_sink_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_bfm_conduit_sink_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_bfm_conduit_sink_valid
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_sink_sink_ready
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_source_bfm_conduit_source_ready
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_source_source_eop
add wave -noupdate -expand /fft_ofdm_tb/fft_ofdm_inst_source_source_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_source_source_exp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_source_source_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_source_source_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_source_source_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst_source_source_valid
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_in_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_in_bus_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_in_bus_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_in_mram
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_out_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_out_bus_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_out_bus_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/a_ram_data_out_mram
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/abuspr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/anb_enabled
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/apr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/apri
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/arch
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/at_data_in_sig
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/at_data_out_sig
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/bfp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/blk_exp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/blk_exp_accum
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/block_done
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/bpb
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/bpr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/byte_enable_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/byte_size
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/cbuspr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/clk
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/clk_ena
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/core_imag_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/core_real_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/count
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_avaliable_sig
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_count
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_count_sig
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_imag_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_imag_in_reg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_imag_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_in_bfp_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_in_bfp_imag_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_in_bfp_imag_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_in_bfp_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_in_bfp_real_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_in_bfp_real_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_in_sig
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_out_sig
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_proc
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_proc_vec
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_rdy
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_rdy_vec
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_real_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_real_in_reg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/data_real_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/del_sop_cnt
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/device_family
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dio
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dio_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dio_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dirn_select
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dpr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dro
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dro_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dro_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dsp_arch
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dsw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/dual_eng_slb
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/en_np
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/eop_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/exp_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/exp_init_fft
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/EXP_WIDTH
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/exponent_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_dirn
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_dirn_held
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_dirn_held_o
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_imag_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_ready_sig
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_real_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_s1_cur
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_s1_next
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_s2_cur
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fft_s2_next
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/FIFO_DEPTH_c
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/first_pass
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/four_idata_bus_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/four_rdata_bus_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/fpr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/FRAME_SIZE
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/FRAME_WORD_WIDTH
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/global_clock_enable
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/go
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/i_ram_data_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/i_ram_data_in_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/i_ram_data_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/i_ram_data_out_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/i_ram_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/i_ram_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/i_wren
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/imag_ram_in_1_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/imag_ram_in_2_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/imag_ram_in_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/imag_ram_out_1_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/imag_ram_out_2_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/imag_ram_out_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/initial_en_np_delay
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/input_data_select
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/input_sample_counter
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/input_selector
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/inv_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/inverse
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/k_count
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/k_count_tw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/k_count_tw_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/k_count_wr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/k_count_wr_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/last_pass_radix
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/log2_n_passes
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/log2_nps
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/lpp_c_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/lpp_data_val
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/lpp_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/lpp_ram_data_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/lpp_rdcnt_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/m512
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_sink_dav
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_sink_ena
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_sink_eop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_sink_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_sink_val
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_source_dav
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_source_ena
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_source_eop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/master_source_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/mem_string
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/mid_apr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/midr2
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/midr2_d
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/mpr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/mram
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/mult_imp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/mult_type
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/n_bfly
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/n_passes
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/n_passes_m1
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/nbc
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/newtw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/next_blk
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/next_input_blk
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/next_pass
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/next_pass_d
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/next_pass_q
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/nps
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/nume
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/oe
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/output_count
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/output_counter
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/p_cd_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/p_count
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/p_tdl
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/quad
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/quad_del
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/quad_del_0
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/quad_del_1
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/quad_del_2
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/r2_lpp_sel
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/ra
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/ram_a_not_b
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/ram_a_not_b_vec
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/ram_data_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/ram_data_in_sw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/ram_data_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/ram_data_out_sw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rb
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rbuspr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rc
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rd
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddr_lpp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddr_lpp_sw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddr_sw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_a_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_a_bus_ctrl
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_a_bus_ctrl_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_a_bus_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_a_bus_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_a_mram
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rdaddress_i_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rden_a
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rden_b
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rden_c
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rden_d
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/real_ram_in_1_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/real_ram_in_2_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/real_ram_in_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/real_ram_out_1_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/real_ram_out_2_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/real_ram_out_dbg
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/reset
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/reset_n
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rfc1
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rfc2
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rfc3
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rfs1
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rfs2
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/rfs3
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sbc
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_addr_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_lpp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_lpp_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_lpp_nm1
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_lpp_o
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_lpp_o_data
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_ram_in
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sel_tw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_eop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_in_work
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_packet_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_ready
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_ready_ctrl
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_ready_ctrl_d
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_stall
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sink_valid
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/slb_last_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/slb_x_o
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/slb_y_o
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sop_d
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sop_de
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sop_det
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sop_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_eop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_exp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_packet_error
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_ready
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_stall
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_stall_d
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_valid
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_valid_ctrl
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/source_valid_ctrl_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/srr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/stall
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/stall_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/start_sop
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sw_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sw_r
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sw_r_tdl
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sw_ra_lpp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sw_rd_lpp
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/sw_w_cd
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/swa_w
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/swd_w
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/switch_read_data
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t1i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t1ie
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t1io
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t1r
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t1re
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t1ro
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t2i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t2ie
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t2io
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t2r
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t2re
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t2ro
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t3i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t3ie
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t3io
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t3r
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t3re
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/t3ro
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twa
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twad
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twad_q
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twade
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twado
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twid_delay
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twiddle_data_imag
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twiddle_data_imag_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twiddle_data_imag_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twiddle_data_real
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twiddle_data_real_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twiddle_data_real_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/twr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/val_o
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/val_out
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/vcc
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wa
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wb
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wc
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wd
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/which_fsm
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/which_ram_set
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/WORD_LENGTH
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wr_ad_delay
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wr_addr_o
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wr_cd_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wr_en_null
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddr
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddr_cd
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddr_cd_en
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddr_cd_sw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddr_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddr_sw
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddress_a_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddress_a_bus_ctrl
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddress_a_bus_ctrl_i
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddress_a_bus_x
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddress_a_bus_y
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddress_a_mram
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wraddress_i_bus
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wren_a
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wren_ad
add wave -noupdate /fft_ofdm_tb/fft_ofdm_inst/fft_ii_0/asj_fft_si_sose_so_b_inst/wren_i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {227131 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 356
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {181422 ps} {350504 ps}
